#!/bin/bash

IMAGE_NAME=micro-gen
BRANCH_NAME=TODO_GET_BRANCH
DOCKER_IMAGE=$IMAGE_NAME:BRANCH_NAME

REPO_NAME=javiersv05
REPO_IMAGE=$REPO_NAME/$IMAGE_NAME:$BRANCH_NAME

docker build -t $DOCKER_IMAGE .
docker tag $DOCKER_IMAGE $REPO_IMAGE